#!/usr/bin/python

from clize import clize, run

@clize
def ping(ident):

	from servo.config import ServoConfig
	from servo.network import ServoNetwork

	config  = ServoConfig()
	network = ServoNetwork(config)

	print network.net.ping(int(ident))

run(ping)
