#!/usr/bin/python

from clize import clize, run

@clize
def set_position(ident, goal, moving_speed=0, max_torque=1023):
	"""
		Set goal_position on a single servo

		ident: Servo id (1-253)

		goal: Position (0-1023)
	"""
	from servo.config import ServoConfig
	from servo.network import ServoNetwork

	config  = ServoConfig()
	network = ServoNetwork(config)

	d = network.get_servo(int(ident))
	print "Current position : %s" % d.current_position
	d.synchronized = False
	d.torque_enable = True
	d.moving_speed = int(moving_speed)
	d.max_torque = int(max_torque)
	d.torque_limit = int(max_torque)
	d.goal_position = int(goal)
	while abs(d.current_position - d.goal_position) > 10:
		print "position", d.current_position

if __name__ == '__main__':
	run(set_position)
