#!/usr/bin/python

from servo.config import ServoConfig
from servo.network import ServoNetwork

config  = ServoConfig()
network = ServoNetwork(config)

network.net.scan(1, 20)
l = network.net.get_dynamixels()
for d in l:
	print d.id

